repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest
        entry: uv run -m pytest
        language: system
        types: [python]
        # files: ^tests/ 
        pass_filenames: false
        always_run: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format